### ISSUE TITLE
Add conda environment

### ISSUE THREAD

**Issue by jonesse3** [JDACS4C-IMPROVE/DeepTTC#10]
It will be useful to the user to include an instruction to create an environment for DeepTTC before running the pip install command. The pip install instructions worked after the update. Thanks!

**Comment by adpartin** [comment]
@AlexandrNP please create instructions to create conda env.

See examples:
- https://github.com/JDACS4C-IMPROVE/GraphDRP?tab=readme-ov-file#2-set-computational-environment
- https://github.com/JDACS4C-IMPROVE/PathDSP?tab=readme-ov-file#2-set-computational-environment

**Comment by AlexandrNP** [comment]
Conda environment is present: https://github.com/JDACS4C-IMPROVE/DeepTTC/blob/develop/environment_no_candle.yml
