### ISSUE TITLE
If use_lincs is set to False, gene_dim doesn't work

### ISSUE THREAD

**Issue by jonesse3** [JDACS4C-IMPROVE/DeepTTC#19]
The gene_dim of 958 doesn't align with the dataset if use_lincs is set to False. I suggest just getting the shape of this dataset when reading it in to avoid having to set the number manually if not using use_lincs = True.

**Comment by AlexandrNP** [comment]
gene_dim should align with the input size. This parameter is needed to avoid making changes to the model as per IMPROVE project goals

**Comment by jonesse3** [comment]
If I don't use use_lincs parameter, which has 958 genes, I have to somehow get the number of genes, which is about 17K.  How is the user supposed to get that number?

**Comment by AlexandrNP** [comment]
Yes, this is correct. Users have to provide input dimensions
